- README.md
> Added important Readme information

- datetimeparser/Parser.py
- datetimeparser/baseclasses.py
- tests/absolute_datetimeformats.py
- tests/absolute_prepositions.py
- tests/relative_datetimes.py
- tests/relative_events.py
- tests/runtests.py
Added `runtests.py` file to run every test (maybe github ci/cl pipeline).
Also added support for `next three days` instread of just `next 3 days`.
Word numbers are currently only counting up to 10.
> Added test support and updated parser

- datetimeparser/Parser.py
- datetimeparser/baseclasses.py
- tests/relative_events.py
Added `Method` enum for specifying mehtod used in parsing (helper for evaluator)
> Added `Method` enum

- .github/workflows/python-app.yml
- README.md
- datetimeparser/Parser.py
- datetimeparser/baseclasses.py
- tests/general_tests.py
- tests/relative_events.py
> Fixed Parser errors and added new constants + testcases

- datetimeparser/Parser.py
- tests/general_tests.py
- tests/relative_events.py
> Fixed issue #29 : absolute prepositions couldnt parse years after events

- datetimeparser/Parser.py
- datetimeparser/baseclasses.py
- tests/absolute_prepositions.py
- tests/runtests.py
- Added multiple values for relative part in absolute_prepositions
- merging of multiple successive time datas with same type in relative part in absolute_prepositions
- general fixing of bugs
- added complex testcases
> Reworked absolute_prepositions for #38

- datetimeparser/Parser.py
- datetimeparser/baseclasses.py
- Added Constants from #45 
- Fixed bug in Parser in absolute prepositions where the Parser couldn't parse a `the` before the absolute part
> Pr #45 and bugfixing in Parser

- datetimeparser/baseclasses.py
> Revert latest changes

- README.md
- datetimeparser/__init__.py
- datetimeparser/datetimeparser.py
Speciefied the imports in __init__ for being able to import datetimeparser as a library
> Edited README file and added `datetimeparser.py` methods + init

- .github/workflows/python-app.yml
- .gitignore
- datetimeparser/baseclasses.py
- datetimeparser/parser.py
- testbot.py
- tests/testcases.py
#76 
- at 9 pm
- at 9 in the morning
- 5 in the evening
- at 05:00
> Added DatetimeDelta Constants parsing

- datetimeparser/baseclasses.py
- datetimeparser/evaluator.py
Added a new Object for the evaluator output (`EvaluatorOutput`)
and improved readability for code + added types for variables
#82
> made code more readable

- datetimeparser/evaluator.py
> changed string into datetime-objects #93

- datetimeparser/evaluatormethods.py
- testbot.py
Fixed a print statement and added the parser result if the evaluator fails in the testbot
> Added better bot output

- requirements.txt
- setup.cfg
- setup.py
Adds
- requirements.txt
- setup.py
- setup.cfg
> Added required files for pypi

- setup.py
> Fixed version number

- datetimeparser/parsermethods.py
Closes #133 
Adds a `parse_int` method to parsermethods.py which checks for an integer respecting negative values
> Added negative integer parsing

- datetimeparser/evaluator.py
- datetimeparser/evaluatormethods.py
- setup.py
- made code more readable
- removed AbsoluteDateTime return (now returns just datetime or int)
- added missing evaluation (Christmas in 2000 years f.e.)
- added comments
> rewrote evaluator

- .flake8
- .github/workflows/python-lint.yml
Changed linting options
- Set max line length to 140 (127 before)
- Removed per-file-ignore from evaluator and parser files
> Changed linting options

- datetimeparser/evaluator.py
- datetimeparser/evaluatormethods.py
- Commented the evaluator code
- None
- None
> Added some comments for Evaluator methods

- tests/runtests.py
- removed unused import
- removed unused argument in functions
- removed sort-parameter (useless)
> fixed codestyle

- datetimeparser/datetimeparser.py
- datetimeparser/evaluatormethods.py
- datetimeparser/evaluatorutils.py
- tests/testcases.py
- weeks now start at monday
- fixed evaluation with preposition `of`
> Rewrite of Evaluator

- .github/workflows/python-tests.yml
- datetimeparser/datetimeparser.py
- datetimeparser/parsermethods.py
- requirements.txt
- tests/testcases.py
> Merge of #171 into main
